### ISSUE TITLE
Stop calling classify() when micro:bit disconnects

### ISSUE THREAD

**Issue by Karlo-Emilo** [microbit-foundation/cctd-ml-machine#191]
The classify function is kept called each second after the input micro:bit is disconnected

It does not have any side effects ro cause errors because of
 if (!currentState.isInputConnected) return;
in the classify function.

But we should probably change this behavior?

**Comment by r59q** [comment]
I think this issue will become stale as of v3.0

**Comment by r59q** [comment]
In the future, the PollingPredictorEngine will keep classifying, even when the micro:bit is disconnected, as it has no knowledge of the microbit, the classifier however will throw an error once the microbit no longer produces input. We should handle this case, but I think the solution is just to do nothing and let the engine keep chugging, skipping the classifications if no data could be found in the live data buffer
