### ISSUE TITLE
Routing is broken

### ISSUE THREAD

**Issue by r59q** [microbit-foundation/cctd-ml-machine#292]
https://ml-machine.org/training -> 404 not found

It seems it is attempting to index on the /training URL. This is only a problem is attempting to access it directly from a URL with a route. This is probably fixed by proper configuration

**Comment by r59q** [comment]
https://stackoverflow.com/questions/57339349/svelte-route-gives-me-404

![image](https://github.com/microbit-foundation/cctd-ml-machine/assets/6570193/439f2487-6810-44ee-b5f1-161a29ef8a59)

**Comment by Karlo-Emilo** [comment]
Yes, it is an Azure Static web apps configuration issue.

I have found a guide on how to fix it, [see here](https://learn.microsoft.com/en-us/shows/azure-tips-and-tricks-static-web-apps/how-to-configure-routing-in-azure-static-web-apps-6-of-16--azure-tips-and-tricks-static-web-apps)

I will look it this week but i think you can fix on your own @r59q. It seems like we just have to add a configuration file. No need to access Azure.
