### ISSUE TITLE
Add button to change to makecode view in model page

### ISSUE THREAD

**Issue by Karlo-Emilo** [microbit-foundation/cctd-ml-machine#308]

**Comment by jaustin** [comment]
Does this mean importing model into MakeCode?

**Comment by Karlo-Emilo** [comment]
> Does this mean importing model into MakeCode?

No, this is to enable block programming around the incoming predictions from the Bluetooth connection.

We have no idea how the model could be imported into MakeCode (We have yet to look at it). I want to discuss it with you soon. We have planned to investigate how a model and the logic generated in our UI (activation of LEDs, pins, and sounds) could be compiled in the browser and transferred to the micro:bit, as we may be able to make that happen in the near future.

The long-term goal, however, should be to have the model on the micro:bit AND enable programming around the model's output in MakeCode, but we do not currently have the capacity to make that happen on our own.

**Comment by r59q** [comment]
Closing this for now, since the identification of the firmware decides which view to use
