### ISSUE TITLE
Persist data representation for predictions until new model is trained

### ISSUE THREAD

**Issue by Karlo-Emilo** [microbit-foundation/cctd-ml-machine#310]
Bug:
- Train model
- Remove or add a filter on the filter inspection page
- Err: The app tries to make a new prediction with the new data representation that is different from the one the model is trained on

**Comment by r59q** [comment]
Refinement:
- Just stop the model for now, when the filters change, indicating to the user that he/she needs to train a new model, that uses the selected filters

**Comment by Karlo-Emilo** [comment]
It looks like we still have the code to persist the MLSettings in ml.ts

`  
// Freeze modelSetting untill next training
  modelSettings = {
    axes: get(settings).includedAxes,
    filters: get(settings).includedFilters,
  };
`

But we are not using this persisted state for classification
