### ISSUE TITLE
Gets into a state where the Chromium bluetooth-connection window does not appear.

### ISSUE THREAD

**Issue by Karlo-Emilo** [microbit-foundation/cctd-ml-machine#325]
The tool sometimes gets into a state where the chromium Bluetooth-connection window does not appear when users click 'connect'.

The issue can be solved by a refresh of the page.

This is an issue on both the main branch and the production branch.

**Comment by r59q** [comment]
Id like some more information about this. Web Bluetooth is still experimental and I have seen this behaviour before when frequently the requestDevice API call, but it appears to be an issue with Chromiums implementation of the protocol

How to replicate?
Does this happen when using the makecode hex?
Any error logs?

**Comment by Karlo-Emilo** [comment]
I can currently not provide more information. It has just been an issue in the last two workshops (one with ml-machine.org and one with main.ml-machine.org), and I have not experienced it beforehand.

But it happens without using the makecode hex (this functionality is not merged into the production branch).

It could of course be a change in the chromium implementation.

**Comment by Karlo-Emilo** [comment]
I will try to replicate it. But I won't have time before next week.

**Comment by r59q** [comment]
Test solution - Introduce polling for services

**Comment by r59q** [comment]
Introduce timeout on 'connecting please wait text'

**Comment by r59q** [comment]
Probably due to reconnect. Microbit disconnects, then firmware is changed, and reconnect is not able to request the device, causing the catastrophic error, where optionalServices are not fetched, leaving the bluetooth protocol broken until page is reloaded.

**Comment by r59q** [comment]
Detect if makecode is open, warn users that this may cause issues. (Code ref: python editor v3 on microbit gh organization)

**Comment by r59q** [comment]
Issue cannot be replicated reliably

**Comment by r59q** [comment]
I am closing this for now, as it is hard to replicate
