### ISSUE TITLE
There should be information on how to update the firmware with the warning

### ISSUE THREAD

**Issue by Karlo-Emilo** [microbit-foundation/cctd-ml-machine#337]
There is currently no information on how to update the firmware when you are warned.

There should be a point at some action the user can do.

And I am unsure. Does it mean you should update the micro:bit version-firmware or just update to the newest version of our program?

**Comment by r59q** [comment]
For makecode .... (explain, but for now just link)

For proprietary popup that leads into the regular connect flow
