### ISSUE TITLE
Hard code axes ranges in filter representations

### ISSUE THREAD

**Issue by Karlo-Emilo** [microbit-foundation/cctd-ml-machine#352]
The axes in the filter representations are currently calculated based o the data samples. This can lead to confusion as different axes may have different ranges in the samle plot.

Instead, we should calculate reasonable ranges for each representation and have them as static configurations.

**Comment by r59q** [comment]
I'm not sure but i think this is solved in #434 

see src/script/utils/FilterLimits.ts

Perhaps we just need to move the limits inside StaticConfiguration?
