### ISSUE TITLE
Outdated firmware warning shows up with the current firmware version

### ISSUE THREAD

**Issue by Karlo-Emilo** [microbit-foundation/cctd-ml-machine#450]
On ml-machine.org (production)

Reproduce:
1) Download the firmware over USB 
2) Disconnect and reconnects the micro:bit
3) The warning shows up in the upper right corner

**Comment by r59q** [comment]
I think this could be caused by dropped Bluetooth messages. Maybe we should attempt to resend messages until some timeout specified.
I would propose the solution of sending the version message 3-5 times during the first 30 seconds of connectivity, that should hopefully make up for any lost messages
