### ISSUE TITLE
Only activate app insights on the  ml-machine.org site

### ISSUE THREAD

**Issue by Karlo-Emilo** [microbit-foundation/cctd-ml-machine#475]
Make sure that data from development activities and forked versions of the repository are not mixed with data from the ml-machine.org site.

The URL is parsed with all tracking data, so it is not a critical issue. We can filter away data from other sources. 

It can, further, be ambiguous that we track data on forked versions (even though the they will always accept our cookie policy before any data are recorded).

@r59q, can we do something in the build process? Similar to what we do with styling?

**Comment by r59q** [comment]
Yes. We can add an entry to the features.json object, with the hostname ml-machine.org and check if it corresponds with `location.hostname` in js 👍 
This implementation should be trivial
