### ISSUE TITLE
Add information about feature flags to the wiki 

### ISSUE THREAD

**Issue by Karlo-Emilo** [microbit-foundation/cctd-ml-machine#497]

**Comment by r59q** [comment]
The goal of feature flags, should ideally only be used for in-progress development, and is subject to frequent change and short life times. I don't think we would like to have these documented in the README, but features that are defined in the features.json file, probably should be documented in the wiki
https://github.com/microbit-foundation/cctd-ml-machine/wiki/Features

**Comment by Karlo-Emilo** [comment]
Then maybe just the instructions to enable all feature flags. I just couldn't find that information, so I had to search in the code base, which is impractical.

I needed it to enable the new features in the preview of a pull request (the current open request).

A wiki page would also work.

**Comment by r59q** [comment]
It has been added to the wiki
