### ISSUE TITLE
Outdated firmware message appears right after downloading the program

### ISSUE THREAD

**Issue by Karlo-Emilo** [microbit-foundation/cctd-ml-machine#516]
Description from a (lead) user:

1. Goto [ml-machine.org](https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fml-machine.org%2F&data=05%7C02%7Ckeb%40cs.au.dk%7C2fe05a6d8c1044ee542208dcb175cd95%7C61fd1d36fecb47cab7d7d0df0370a198%7C1%7C0%7C638580366736325102%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=OFKGKo1JdivvvdOoZl5c94Es4CWcvmOhUacyIszal%2B4%3D&reserved=0)
2. Select Connect your micro:bit
3. Select Download, next, Find USB unit, connect [download takes place]
4. Select Connect using Bluetooth, verify pattern, select Connect, Pair [micro:bit successfully paired]
5. Error appears Your micro:bit firmware is outdated (see image)

 It only appears the first time the user pairs a new micro:bit.

**Comment by r59q** [comment]
I think we should disable this for the time being, due to it's innacuracy. Sometimes the UART messages won't be delivered, not sure why.
