### ISSUE TITLE
Show raw values when hovering over the recorded sample-graphs

### ISSUE THREAD

**Issue by Karlo-Emilo** [microbit-foundation/cctd-ml-machine#535]
It may be instead of showing the 3D animation of the micro:bit, or it may be possible to show both.

Show the numbers with two decimal precision.

@r59q, it would be nice, if you can prioritise this one and #534, so we have a demo before October 28, where we have a workshop with teachers. We will not test it in a classroom before december, so the demo does not have to be super stable or finished for October 28.

**Comment by r59q** [comment]
Fixed as of v3.3
